channels:
  뉴스엔진:
    subscriber: 342000
    age:
      10대: 0
      20대: 1
      30대: 3
      40대: 4
      50대: 32
      60대이상: 46
    gender:
      여성: 55
      남성: 45
    device:
      모바일: 78
      TV: 0
      PC: 22
      태블릿: 0
    interests:
      - 건강
      - 식품
      - 트로트
      - 시사
    categories:
      - 식품
      - 생활건강

신사임당:
    subscriber: 2710000
    age:
      10대: 0
      20대: 0.4
      30대: 3.8
      40대: 9.6
      50대: 26.1
      55-64세: 33.9
      60대이상: 26.2
    gender:
      여성: 24.0
      남성: 75.9
    device:
      모바일: 72.3
      TV: 10.7
      PC: 9.4
      태블릿: 7.5
    interests:
      - 시사
      - 경제
      - 국방
      - 재테크
      - 부업
      - 건강
    categories:
      - 식품
      - 생활건강